services:
  mssqldata:
    build: .
    image: microstoreimages.azurecr.io/mcr.microsoft.com/mssql/server:2022-latest    
    networks:
      - backend
  rabbitmq:
    build: .
    image: microstoreimages.azurecr.io/rabbitmq:3-management-alpine
    networks:
      - backend
  seq:
    build: .
    image: microstoreimages.azurecr.io/datalust/seq:latest
  products:
    build: .
    image: microstoreimages.azurecr.io/microstore-products:latest
    depends_on:
      - mssqldata
    networks:
      - backend 
  inventory:
    build: .
    image: microstoreimages.azurecr.io/microstore-inventory:latest
    depends_on:
      - mssqldata
      - rabbitmq
    networks:
      - backend
  auth:
    build: .
    image: microstoreimages.azurecr.io/microstore-auth:latest
    depends_on:
      - rabbitmq
      - mssqldata
    networks:
      - backend
  shoppingcart:
    build: .
    image: microstoreimages.azurecr.io/microstore-shoppingcart:latest
    depends_on:
      - mssqldata
    networks:
      - backend
  coupon:
    build: .
    image: microstoreimages.azurecr.io/microstore-coupon:latest
    depends_on:
      - mssqldata
    networks:
      - backend
  comments:
    build: .
    image: microstoreimages.azurecr.io/microstore-comments:latest
    depends_on:
      - mssqldata
    networks:
      - backend
  order:
    build: .
    image: microstoreimages.azurecr.io/microstore-order:latest
    depends_on:
      - mssqldata
    networks:
      - backend
  chatbot:
    build: .
    image: microstoreimages.azurecr.io/microstore-chatbot:latest
    networks:
      - backend
  gateway:
    build: .
    image: microstoreimages.azurecr.io/microstore-gateway:latest
    depends_on:
      - products
      - shoppingcart
      - coupon 
      - comments 
      - inventory  
    networks:
      - backend
  gatewayadmin:
    build: .
    image: microstoreimages.azurecr.io/microstore-gatewayadmin:latest
    depends_on:
      - products
      - shoppingcart
      - coupon 
      - comments 
      - inventory  
    networks:
      - backend

networks:
  backend:
    driver: bridge