version: '3.9'
services:
  mssqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest    
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - backend
  seq:
    image: datalust/seq:latest
  products:
    build:
      context: .
      dockerfile: microStore.Services.ProductApi/Dockerfile
    depends_on:
      - mssqldata
    networks:
      - backend 
  inventory:
    build:
      context: .
      dockerfile: microStore.Services.InventoryApi/Dockerfile
    depends_on:
      - mssqldata
      - rabbitmq
    networks:
      - backend
  auth:
    build:
      context: .
      dockerfile: microStore.Services.AuthApi/Dockerfile
    depends_on:
      - mssqldata
    networks:
      - backend
  shoppingcart:
    build:
      context: .
      dockerfile: microStore.Services.ShoppingCartApi/Dockerfile
    depends_on:
      - mssqldata
    networks:
      - backend
  coupon:
    build:
      context: .
      dockerfile: microStore.Services.CouponApi/Dockerfile
    depends_on:
      - mssqldata
    networks:
      - backend
  comments:
    build:
      context: .
      dockerfile: microStore.Services.CommentApi/Dockerfile
    depends_on:
      - mssqldata
    networks:
      - backend
  order:
    build:
      context: .
      dockerfile: microStore.Services.OrderApi/Dockerfile
    depends_on:
      - mssqldata
    networks:
      - backend
  chatbot:
    build:
      context: .
      dockerfile: microstore.Chatbot/Dockerfile
    networks:
      - backend
  gateway:
    build:
      context: .
      dockerfile: microStore.ApiGateway/Dockerfile
    depends_on:
      - products
      - shoppingcart
      - coupon 
      - comments 
      - inventory  
    networks:
      - backend
  gatewayadmin:
    build:
      context: .
      dockerfile: ApiAdminGateway/Dockerfile
    depends_on:
      - products
      - shoppingcart
      - coupon 
      - comments 
      - inventory  
    networks:
      - backend

networks:
  backend:
    driver: bridge