// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using microStore.Services.CouponApi.Data;

#nullable disable

namespace microStore.Services.CouponApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("microStore.Services.CouponApi.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<int>("ActivationCount")
                        .HasColumnType("int");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountAmount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons", (string)null);

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            ActivationCount = 1,
                            CouponCode = "Puto1",
                            DiscountAmount = 30,
                            ExpirationDate = new DateTime(2024, 4, 8, 20, 39, 11, 511, DateTimeKind.Local).AddTicks(8417),
                            MinAmount = 10
                        },
                        new
                        {
                            CouponId = 2,
                            ActivationCount = 1,
                            CouponCode = "Puto2",
                            DiscountAmount = 35,
                            ExpirationDate = new DateTime(2024, 4, 8, 20, 39, 11, 511, DateTimeKind.Local).AddTicks(8451),
                            MinAmount = 20
                        },
                        new
                        {
                            CouponId = 3,
                            ActivationCount = 1,
                            CouponCode = "Puto3",
                            DiscountAmount = 40,
                            ExpirationDate = new DateTime(2024, 4, 8, 20, 39, 11, 511, DateTimeKind.Local).AddTicks(8463),
                            MinAmount = 10
                        },
                        new
                        {
                            CouponId = 4,
                            ActivationCount = 1,
                            CouponCode = "Puto4",
                            DiscountAmount = 20,
                            ExpirationDate = new DateTime(2024, 4, 8, 20, 39, 11, 511, DateTimeKind.Local).AddTicks(8475),
                            MinAmount = 80
                        },
                        new
                        {
                            CouponId = 5,
                            ActivationCount = 1,
                            CouponCode = "Puto5",
                            DiscountAmount = 10,
                            ExpirationDate = new DateTime(2024, 4, 8, 20, 39, 11, 511, DateTimeKind.Local).AddTicks(8486),
                            MinAmount = 56
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
