// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using microStore.Services.ProductApi.Data;

#nullable disable

namespace microStore.Services.ProductApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250116151253_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 3
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 4
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 5
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 6
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 6,
                            ProductId = 7
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 6,
                            ProductId = 8
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 7,
                            ProductId = 9
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 10
                        },
                        new
                        {
                            CategoryId = 4,
                            ProductId = 10
                        },
                        new
                        {
                            CategoryId = 7,
                            ProductId = 10
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 11
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 11
                        },
                        new
                        {
                            CategoryId = 8,
                            ProductId = 11
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 12
                        },
                        new
                        {
                            CategoryId = 5,
                            ProductId = 12
                        },
                        new
                        {
                            CategoryId = 8,
                            ProductId = 12
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 13
                        },
                        new
                        {
                            CategoryId = 6,
                            ProductId = 13
                        },
                        new
                        {
                            CategoryId = 9,
                            ProductId = 13
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 14
                        },
                        new
                        {
                            CategoryId = 6,
                            ProductId = 14
                        },
                        new
                        {
                            CategoryId = 9,
                            ProductId = 14
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 15
                        },
                        new
                        {
                            CategoryId = 7,
                            ProductId = 15
                        },
                        new
                        {
                            CategoryId = 10,
                            ProductId = 15
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 16
                        },
                        new
                        {
                            CategoryId = 7,
                            ProductId = 16
                        },
                        new
                        {
                            CategoryId = 10,
                            ProductId = 16
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 17
                        },
                        new
                        {
                            CategoryId = 7,
                            ProductId = 17
                        },
                        new
                        {
                            CategoryId = 11,
                            ProductId = 17
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 18
                        },
                        new
                        {
                            CategoryId = 7,
                            ProductId = 18
                        },
                        new
                        {
                            CategoryId = 11,
                            ProductId = 18
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 19
                        },
                        new
                        {
                            CategoryId = 9,
                            ProductId = 19
                        },
                        new
                        {
                            CategoryId = 12,
                            ProductId = 19
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 20
                        },
                        new
                        {
                            CategoryId = 9,
                            ProductId = 20
                        },
                        new
                        {
                            CategoryId = 12,
                            ProductId = 20
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 21
                        },
                        new
                        {
                            CategoryId = 10,
                            ProductId = 21
                        },
                        new
                        {
                            CategoryId = 13,
                            ProductId = 21
                        },
                        new
                        {
                            CategoryId = 1,
                            ProductId = 22
                        },
                        new
                        {
                            CategoryId = 10,
                            ProductId = 22
                        },
                        new
                        {
                            CategoryId = 13,
                            ProductId = 22
                        });
                });

            modelBuilder.Entity("ProductPropertyValue", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyValueId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "PropertyValueId");

                    b.HasIndex("PropertyValueId");

                    b.ToTable("ProductPropertyValue");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            PropertyValueId = 3
                        },
                        new
                        {
                            ProductId = 1,
                            PropertyValueId = 7
                        },
                        new
                        {
                            ProductId = 1,
                            PropertyValueId = 9
                        },
                        new
                        {
                            ProductId = 2,
                            PropertyValueId = 4
                        },
                        new
                        {
                            ProductId = 2,
                            PropertyValueId = 7
                        },
                        new
                        {
                            ProductId = 2,
                            PropertyValueId = 10
                        },
                        new
                        {
                            ProductId = 3,
                            PropertyValueId = 3
                        },
                        new
                        {
                            ProductId = 3,
                            PropertyValueId = 38
                        },
                        new
                        {
                            ProductId = 4,
                            PropertyValueId = 7
                        },
                        new
                        {
                            ProductId = 4,
                            PropertyValueId = 39
                        },
                        new
                        {
                            ProductId = 5,
                            PropertyValueId = 21
                        },
                        new
                        {
                            ProductId = 5,
                            PropertyValueId = 17
                        },
                        new
                        {
                            ProductId = 5,
                            PropertyValueId = 26
                        },
                        new
                        {
                            ProductId = 6,
                            PropertyValueId = 23
                        },
                        new
                        {
                            ProductId = 6,
                            PropertyValueId = 18
                        },
                        new
                        {
                            ProductId = 6,
                            PropertyValueId = 24
                        },
                        new
                        {
                            ProductId = 7,
                            PropertyValueId = 27
                        },
                        new
                        {
                            ProductId = 7,
                            PropertyValueId = 29
                        },
                        new
                        {
                            ProductId = 8,
                            PropertyValueId = 30
                        },
                        new
                        {
                            ProductId = 8,
                            PropertyValueId = 27
                        },
                        new
                        {
                            ProductId = 9,
                            PropertyValueId = 19
                        },
                        new
                        {
                            ProductId = 9,
                            PropertyValueId = 7
                        },
                        new
                        {
                            ProductId = 10,
                            PropertyValueId = 19
                        },
                        new
                        {
                            ProductId = 10,
                            PropertyValueId = 6
                        },
                        new
                        {
                            ProductId = 11,
                            PropertyValueId = 34
                        },
                        new
                        {
                            ProductId = 11,
                            PropertyValueId = 32
                        },
                        new
                        {
                            ProductId = 12,
                            PropertyValueId = 34
                        },
                        new
                        {
                            ProductId = 12,
                            PropertyValueId = 31
                        },
                        new
                        {
                            ProductId = 13,
                            PropertyValueId = 35
                        },
                        new
                        {
                            ProductId = 13,
                            PropertyValueId = 37
                        },
                        new
                        {
                            ProductId = 14,
                            PropertyValueId = 35
                        },
                        new
                        {
                            ProductId = 14,
                            PropertyValueId = 38
                        },
                        new
                        {
                            ProductId = 15,
                            PropertyValueId = 37
                        },
                        new
                        {
                            ProductId = 16,
                            PropertyValueId = 37
                        },
                        new
                        {
                            ProductId = 17,
                            PropertyValueId = 37
                        },
                        new
                        {
                            ProductId = 18,
                            PropertyValueId = 37
                        },
                        new
                        {
                            ProductId = 19,
                            PropertyValueId = 38
                        },
                        new
                        {
                            ProductId = 20,
                            PropertyValueId = 38
                        },
                        new
                        {
                            ProductId = 21,
                            PropertyValueId = 35
                        },
                        new
                        {
                            ProductId = 22,
                            PropertyValueId = 36
                        });
                });

            modelBuilder.Entity("microStore.Services.ProductApi.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandName = "Samsung"
                        },
                        new
                        {
                            Id = 2,
                            BrandName = "LG"
                        },
                        new
                        {
                            Id = 3,
                            BrandName = "Sony"
                        },
                        new
                        {
                            Id = 4,
                            BrandName = "Panasonic"
                        },
                        new
                        {
                            Id = 5,
                            BrandName = "Lenovo"
                        },
                        new
                        {
                            Id = 6,
                            BrandName = "HP"
                        },
                        new
                        {
                            Id = 7,
                            BrandName = "Dell"
                        },
                        new
                        {
                            Id = 8,
                            BrandName = "Bose"
                        },
                        new
                        {
                            Id = 9,
                            BrandName = "JBL"
                        },
                        new
                        {
                            Id = 10,
                            BrandName = "Apple"
                        },
                        new
                        {
                            Id = 11,
                            BrandName = "Xiaomi"
                        },
                        new
                        {
                            Id = 12,
                            BrandName = "Whirlpool"
                        },
                        new
                        {
                            Id = 13,
                            BrandName = "Daikin"
                        },
                        new
                        {
                            Id = 14,
                            BrandName = "Samsung Appliances"
                        },
                        new
                        {
                            Id = 15,
                            BrandName = "IKEA"
                        },
                        new
                        {
                            Id = 16,
                            BrandName = "Ashley Furniture"
                        },
                        new
                        {
                            Id = 17,
                            BrandName = "Bridgestone"
                        },
                        new
                        {
                            Id = 18,
                            BrandName = "Goodyear"
                        },
                        new
                        {
                            Id = 19,
                            BrandName = "Michelin"
                        },
                        new
                        {
                            Id = 20,
                            BrandName = "Bosch"
                        });
                });

            modelBuilder.Entity("microStore.Services.ProductApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryLevel")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryLevel = 0,
                            CategoryName = "Tecnologia",
                            CategoryParentId = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryLevel = 1,
                            CategoryName = "TV, Audio y Video",
                            CategoryParentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryLevel = 2,
                            CategoryName = "Televisores",
                            CategoryParentId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryLevel = 2,
                            CategoryName = "Accesorios TV",
                            CategoryParentId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryLevel = 1,
                            CategoryName = "Computadores y Accesorios",
                            CategoryParentId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryLevel = 2,
                            CategoryName = "Computadores Portátiles",
                            CategoryParentId = 5
                        },
                        new
                        {
                            Id = 7,
                            CategoryLevel = 1,
                            CategoryName = "Audio y Video",
                            CategoryParentId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryLevel = 2,
                            CategoryName = "Parlantes",
                            CategoryParentId = 7
                        },
                        new
                        {
                            Id = 9,
                            CategoryLevel = 1,
                            CategoryName = "Celulares",
                            CategoryParentId = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryLevel = 2,
                            CategoryName = "Smartphones",
                            CategoryParentId = 9
                        },
                        new
                        {
                            Id = 11,
                            CategoryLevel = 0,
                            CategoryName = "Electrodomésticos",
                            CategoryParentId = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryLevel = 1,
                            CategoryName = "Climatización",
                            CategoryParentId = 11
                        },
                        new
                        {
                            Id = 13,
                            CategoryLevel = 2,
                            CategoryName = "Aires Acondicionados",
                            CategoryParentId = 12
                        },
                        new
                        {
                            Id = 14,
                            CategoryLevel = 1,
                            CategoryName = "Cocina",
                            CategoryParentId = 11
                        },
                        new
                        {
                            Id = 15,
                            CategoryLevel = 2,
                            CategoryName = "Hornos",
                            CategoryParentId = 14
                        },
                        new
                        {
                            Id = 16,
                            CategoryLevel = 0,
                            CategoryName = "Muebles",
                            CategoryParentId = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryLevel = 1,
                            CategoryName = "Muebles de Dormitorio",
                            CategoryParentId = 16
                        },
                        new
                        {
                            Id = 18,
                            CategoryLevel = 2,
                            CategoryName = "Armarios y Closets",
                            CategoryParentId = 17
                        },
                        new
                        {
                            Id = 19,
                            CategoryLevel = 2,
                            CategoryName = "Camas y Basecamas",
                            CategoryParentId = 17
                        },
                        new
                        {
                            Id = 20,
                            CategoryLevel = 0,
                            CategoryName = "Automóvil",
                            CategoryParentId = 0
                        },
                        new
                        {
                            Id = 21,
                            CategoryLevel = 1,
                            CategoryName = "Llantas",
                            CategoryParentId = 20
                        },
                        new
                        {
                            Id = 22,
                            CategoryLevel = 2,
                            CategoryName = "Llantas Carro",
                            CategoryParentId = 21
                        },
                        new
                        {
                            Id = 23,
                            CategoryLevel = 1,
                            CategoryName = "Accesorios Carro",
                            CategoryParentId = 20
                        },
                        new
                        {
                            Id = 24,
                            CategoryLevel = 2,
                            CategoryName = "Batería de Auto",
                            CategoryParentId = 23
                        });
                });

            modelBuilder.Entity("microStore.Services.ProductApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<decimal>("Current_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Previous_price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Current_price = 2500000m,
                            Description = "Televisor Samsung de 55 pulgadas con resolución 4K y tecnología HDR.",
                            IsAvailable = true,
                            Name = "Smart TV Samsung 55\"",
                            Previous_price = 3000000m
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            Current_price = 4500000m,
                            Description = "Televisor LG OLED de 65 pulgadas con tecnología AI ThinQ.",
                            IsAvailable = true,
                            Name = "Televisor LG OLED 65\"",
                            Previous_price = 5000000m
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            Current_price = 100000m,
                            Description = "Soporte universal para televisores de hasta 55 pulgadas, fácil instalación.",
                            IsAvailable = true,
                            Name = "Soporte para TV hasta 55\"",
                            Previous_price = 150000m
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 4,
                            Current_price = 50000m,
                            Description = "Cable HDMI 2.1 de 3 metros, compatible con resolución 4K y 8K.",
                            IsAvailable = true,
                            Name = "Cable HDMI 4K 3 metros",
                            Previous_price = 80000m
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 5,
                            Current_price = 3200000m,
                            Description = "Portátil Lenovo ThinkPad con procesador Intel Core i5 y 8GB de RAM.",
                            IsAvailable = true,
                            Name = "Portátil Lenovo ThinkPad",
                            Previous_price = 3500000m
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 6,
                            Current_price = 2800000m,
                            Description = "Portátil HP Pavilion con pantalla Full HD y disco SSD de 256GB.",
                            IsAvailable = true,
                            Name = "Portátil HP Pavilion",
                            Previous_price = 3200000m
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 8,
                            Current_price = 600000m,
                            Description = "Parlante portátil Bose con conexión Bluetooth y sonido premium.",
                            IsAvailable = true,
                            Name = "Bocina Bose SoundLink",
                            Previous_price = 700000m
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 9,
                            Current_price = 450000m,
                            Description = "Parlante portátil JBL con batería de larga duración y diseño resistente al agua.",
                            IsAvailable = true,
                            Name = "Parlante JBL Flip 5",
                            Previous_price = 500000m
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 10,
                            Current_price = 5500000m,
                            Description = "Smartphone Apple iPhone 14 Pro con cámara de 48 MP y 256GB de almacenamiento.",
                            IsAvailable = true,
                            Name = "iPhone 14 Pro",
                            Previous_price = 6000000m
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 11,
                            Current_price = 1200000m,
                            Description = "Smartphone Xiaomi con pantalla AMOLED y procesador Snapdragon 685.",
                            IsAvailable = true,
                            Name = "Xiaomi Redmi Note 12",
                            Previous_price = 1500000m
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 14,
                            Current_price = 1800000m,
                            Description = "Aire acondicionado Samsung de 12000 BTU, ideal para habitaciones medianas.",
                            IsAvailable = true,
                            Name = "Aire Acondicionado Samsung",
                            Previous_price = 2000000m
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 13,
                            Current_price = 2400000m,
                            Description = "Aire acondicionado Daikin con tecnología inverter y bajo consumo energético.",
                            IsAvailable = true,
                            Name = "Aire Acondicionado Daikin",
                            Previous_price = 2800000m
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 12,
                            Current_price = 350000m,
                            Description = "Horno microondas Whirlpool de 20 litros con función grill.",
                            IsAvailable = true,
                            Name = "Horno Microondas Whirlpool",
                            Previous_price = 450000m
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 14,
                            Current_price = 400000m,
                            Description = "Horno eléctrico Oster de 25 litros, ideal para hornear y tostar.",
                            IsAvailable = true,
                            Name = "Horno Eléctrico Oster",
                            Previous_price = 500000m
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 15,
                            Current_price = 1500000m,
                            Description = "Armario IKEA Pax modular con diseño minimalista y amplio espacio de almacenamiento.",
                            IsAvailable = true,
                            Name = "Armario IKEA Pax",
                            Previous_price = 1800000m
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 16,
                            Current_price = 2000000m,
                            Description = "Closet Ashley Furniture con puertas corredizas y diseño elegante.",
                            IsAvailable = true,
                            Name = "Closet Ashley Furniture",
                            Previous_price = 2300000m
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 16,
                            Current_price = 800000m,
                            Description = "Basecama king size con estructura resistente y diseño moderno.",
                            IsAvailable = true,
                            Name = "Basecama King Size",
                            Previous_price = 1000000m
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 15,
                            Current_price = 1200000m,
                            Description = "Cama doble de madera maciza con acabado natural.",
                            IsAvailable = true,
                            Name = "Cama Doble Madera",
                            Previous_price = 1400000m
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 17,
                            Current_price = 350000m,
                            Description = "Llanta Bridgestone para automóvil, tamaño 16 pulgadas.",
                            IsAvailable = true,
                            Name = "Llanta Bridgestone 16\"",
                            Previous_price = 400000m
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 18,
                            Current_price = 400000m,
                            Description = "Llanta Goodyear para SUV, tamaño 17 pulgadas.",
                            IsAvailable = true,
                            Name = "Llanta Goodyear 17\"",
                            Previous_price = 450000m
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 20,
                            Current_price = 500000m,
                            Description = "Batería para automóvil Bosch con capacidad de 12V y 70Ah.",
                            IsAvailable = true,
                            Name = "Batería Bosch 12V",
                            Previous_price = 600000m
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 19,
                            Current_price = 450000m,
                            Description = "Batería de auto Energizer con alto rendimiento y larga duración.",
                            IsAvailable = true,
                            Name = "Batería de Auto Energizer",
                            Previous_price = 550000m
                        });
                });

            modelBuilder.Entity("microStore.Services.ProductApi.Models.ProductImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 11,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 12,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 13,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 14,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 15,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 16,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 17,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 18,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 18
                        },
                        new
                        {
                            Id = 19,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 19
                        },
                        new
                        {
                            Id = 20,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 21,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 21
                        },
                        new
                        {
                            Id = 22,
                            ImageLabel = "image1",
                            ImageUrl = "https://www.alkosto.com/medias/8806091857859-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzODUwNnxpbWFnZS93ZWJwfGFEQXdMMmcwWWk4eE5EYzBOVFF6TXpNME1UazRNaTg0T0RBMk1Ea3hPRFUzT0RVNVh6QXdNVjgzTlRCWGVEYzFNRWd8NTU0MDIwYmI1YTZkZjc0MmIyYWU0YmZjMzIyNjM0N2VmZWRjNDMxYTJlYThlNWQyMmExMWI4OTFkOWY4ZTY0OA",
                            ProductId = 22
                        });
                });

            modelBuilder.Entity("microStore.Services.ProductApi.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("bit");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyOrder")
                        .HasColumnType("int");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPrincipal = false,
                            PropertyName = "Tamaño de Pantalla",
                            PropertyOrder = 1,
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsPrincipal = false,
                            PropertyName = "Resolución",
                            PropertyOrder = 2,
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsPrincipal = false,
                            PropertyName = "Tipo de Pantalla",
                            PropertyOrder = 3,
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsPrincipal = false,
                            PropertyName = "HDMI",
                            PropertyOrder = 1,
                            PropertyTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsPrincipal = false,
                            PropertyName = "Conectividad Bluetooth",
                            PropertyOrder = 2,
                            PropertyTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            IsPrincipal = false,
                            PropertyName = "HDR",
                            PropertyOrder = 3,
                            PropertyTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            IsPrincipal = false,
                            PropertyName = "Control Remoto",
                            PropertyOrder = 1,
                            PropertyTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            IsPrincipal = false,
                            PropertyName = "Puertos HDMI",
                            PropertyOrder = 2,
                            PropertyTypeId = 3
                        },
                        new
                        {
                            Id = 9,
                            IsPrincipal = false,
                            PropertyName = "Memoria RAM",
                            PropertyOrder = 4,
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            IsPrincipal = false,
                            PropertyName = "Procesador",
                            PropertyOrder = 5,
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            IsPrincipal = false,
                            PropertyName = "Sistema Operativo",
                            PropertyOrder = 6,
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            IsPrincipal = false,
                            PropertyName = "Duración de Batería",
                            PropertyOrder = 4,
                            PropertyTypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            IsPrincipal = false,
                            PropertyName = "Conectividad Wi-Fi",
                            PropertyOrder = 5,
                            PropertyTypeId = 2
                        },
                        new
                        {
                            Id = 14,
                            IsPrincipal = false,
                            PropertyName = "Puertos USB",
                            PropertyOrder = 3,
                            PropertyTypeId = 3
                        },
                        new
                        {
                            Id = 15,
                            IsPrincipal = false,
                            PropertyName = "Capacidad de Almacenamiento",
                            PropertyOrder = 7,
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 16,
                            IsPrincipal = false,
                            PropertyName = "Cámara",
                            PropertyOrder = 6,
                            PropertyTypeId = 2
                        },
                        new
                        {
                            Id = 17,
                            IsPrincipal = false,
                            PropertyName = "Carga Rápida",
                            PropertyOrder = 7,
                            PropertyTypeId = 2
                        },
                        new
                        {
                            Id = 18,
                            IsPrincipal = false,
                            PropertyName = "Tecnología Inverter",
                            PropertyOrder = 8,
                            PropertyTypeId = 2
                        },
                        new
                        {
                            Id = 19,
                            IsPrincipal = false,
                            PropertyName = "Eficiencia Energética",
                            PropertyOrder = 8,
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 20,
                            IsPrincipal = false,
                            PropertyName = "Capacidad",
                            PropertyOrder = 9,
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 21,
                            IsPrincipal = false,
                            PropertyName = "Programas de Cocción",
                            PropertyOrder = 9,
                            PropertyTypeId = 2
                        },
                        new
                        {
                            Id = 22,
                            IsPrincipal = false,
                            PropertyName = "Material de la Cava",
                            PropertyOrder = 4,
                            PropertyTypeId = 3
                        },
                        new
                        {
                            Id = 23,
                            IsPrincipal = false,
                            PropertyName = "Potencia de Salida",
                            PropertyOrder = 10,
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 24,
                            IsPrincipal = false,
                            PropertyName = "Impermeable",
                            PropertyOrder = 10,
                            PropertyTypeId = 2
                        },
                        new
                        {
                            Id = 25,
                            IsPrincipal = false,
                            PropertyName = "Dimensiones",
                            PropertyOrder = 11,
                            PropertyTypeId = 1
                        },
                        new
                        {
                            Id = 26,
                            IsPrincipal = false,
                            PropertyName = "Material",
                            PropertyOrder = 5,
                            PropertyTypeId = 3
                        });
                });

            modelBuilder.Entity("microStore.Services.ProductApi.Models.PropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PropertyTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyTypeOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PropertyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PropertyTypeDescription = "Caracteristicas mas destacables de los productos",
                            PropertyTypeName = "Caracteristicas Principales",
                            PropertyTypeOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            PropertyTypeDescription = "Funciones principales de los productos",
                            PropertyTypeName = "Funciones",
                            PropertyTypeOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            PropertyTypeDescription = "Componentes que componen el producto",
                            PropertyTypeName = "Componentes",
                            PropertyTypeOrder = 3
                        });
                });

            modelBuilder.Entity("microStore.Services.ProductApi.Models.PropertyValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyValueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PropertyId = 1,
                            PropertyValueName = "32 pulgadas"
                        },
                        new
                        {
                            Id = 2,
                            PropertyId = 1,
                            PropertyValueName = "43 pulgadas"
                        },
                        new
                        {
                            Id = 3,
                            PropertyId = 1,
                            PropertyValueName = "55 pulgadas"
                        },
                        new
                        {
                            Id = 4,
                            PropertyId = 1,
                            PropertyValueName = "65 pulgadas"
                        },
                        new
                        {
                            Id = 5,
                            PropertyId = 2,
                            PropertyValueName = "HD"
                        },
                        new
                        {
                            Id = 6,
                            PropertyId = 2,
                            PropertyValueName = "Full HD"
                        },
                        new
                        {
                            Id = 7,
                            PropertyId = 2,
                            PropertyValueName = "4K Ultra HD"
                        },
                        new
                        {
                            Id = 8,
                            PropertyId = 2,
                            PropertyValueName = "8K Ultra HD"
                        },
                        new
                        {
                            Id = 9,
                            PropertyId = 3,
                            PropertyValueName = "LED"
                        },
                        new
                        {
                            Id = 10,
                            PropertyId = 3,
                            PropertyValueName = "OLED"
                        },
                        new
                        {
                            Id = 11,
                            PropertyId = 3,
                            PropertyValueName = "QLED"
                        },
                        new
                        {
                            Id = 12,
                            PropertyId = 3,
                            PropertyValueName = "IPS"
                        },
                        new
                        {
                            Id = 13,
                            PropertyId = 8,
                            PropertyValueName = "2 Puertos"
                        },
                        new
                        {
                            Id = 14,
                            PropertyId = 8,
                            PropertyValueName = "3 Puertos"
                        },
                        new
                        {
                            Id = 15,
                            PropertyId = 8,
                            PropertyValueName = "4 Puertos"
                        },
                        new
                        {
                            Id = 16,
                            PropertyId = 9,
                            PropertyValueName = "4GB"
                        },
                        new
                        {
                            Id = 17,
                            PropertyId = 9,
                            PropertyValueName = "8GB"
                        },
                        new
                        {
                            Id = 18,
                            PropertyId = 9,
                            PropertyValueName = "16GB"
                        },
                        new
                        {
                            Id = 19,
                            PropertyId = 9,
                            PropertyValueName = "32GB"
                        },
                        new
                        {
                            Id = 20,
                            PropertyId = 10,
                            PropertyValueName = "Intel Core i3"
                        },
                        new
                        {
                            Id = 21,
                            PropertyId = 10,
                            PropertyValueName = "Intel Core i5"
                        },
                        new
                        {
                            Id = 22,
                            PropertyId = 10,
                            PropertyValueName = "Intel Core i7"
                        },
                        new
                        {
                            Id = 23,
                            PropertyId = 10,
                            PropertyValueName = "Ryzen 5"
                        },
                        new
                        {
                            Id = 24,
                            PropertyId = 15,
                            PropertyValueName = "512GB SSD"
                        },
                        new
                        {
                            Id = 25,
                            PropertyId = 15,
                            PropertyValueName = "1TB HDD"
                        },
                        new
                        {
                            Id = 26,
                            PropertyId = 15,
                            PropertyValueName = "256GB SSD"
                        },
                        new
                        {
                            Id = 27,
                            PropertyId = 13,
                            PropertyValueName = "Wi-Fi 5"
                        },
                        new
                        {
                            Id = 28,
                            PropertyId = 13,
                            PropertyValueName = "Wi-Fi 6"
                        },
                        new
                        {
                            Id = 29,
                            PropertyId = 12,
                            PropertyValueName = "10 horas"
                        },
                        new
                        {
                            Id = 30,
                            PropertyId = 12,
                            PropertyValueName = "15 horas"
                        },
                        new
                        {
                            Id = 31,
                            PropertyId = 19,
                            PropertyValueName = "Eficiencia A"
                        },
                        new
                        {
                            Id = 32,
                            PropertyId = 19,
                            PropertyValueName = "Eficiencia A+"
                        },
                        new
                        {
                            Id = 33,
                            PropertyId = 20,
                            PropertyValueName = "5000 BTU"
                        },
                        new
                        {
                            Id = 34,
                            PropertyId = 20,
                            PropertyValueName = "12000 BTU"
                        },
                        new
                        {
                            Id = 35,
                            PropertyId = 23,
                            PropertyValueName = "2000W"
                        },
                        new
                        {
                            Id = 36,
                            PropertyId = 23,
                            PropertyValueName = "5000W"
                        },
                        new
                        {
                            Id = 37,
                            PropertyId = 26,
                            PropertyValueName = "Madera"
                        },
                        new
                        {
                            Id = 38,
                            PropertyId = 26,
                            PropertyValueName = "Metal"
                        },
                        new
                        {
                            Id = 39,
                            PropertyId = 26,
                            PropertyValueName = "Plástico"
                        });
                });

            modelBuilder.Entity("ProductCategory", b =>
                {
                    b.HasOne("microStore.Services.ProductApi.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("microStore.Services.ProductApi.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductPropertyValue", b =>
                {
                    b.HasOne("microStore.Services.ProductApi.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("microStore.Services.ProductApi.Models.PropertyValue", null)
                        .WithMany()
                        .HasForeignKey("PropertyValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("microStore.Services.ProductApi.Models.Product", b =>
                {
                    b.HasOne("microStore.Services.ProductApi.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("microStore.Services.ProductApi.Models.ProductImages", b =>
                {
                    b.HasOne("microStore.Services.ProductApi.Models.Product", "Products")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("microStore.Services.ProductApi.Models.Property", b =>
                {
                    b.HasOne("microStore.Services.ProductApi.Models.PropertyType", "PropertyType")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyType");
                });

            modelBuilder.Entity("microStore.Services.ProductApi.Models.PropertyValue", b =>
                {
                    b.HasOne("microStore.Services.ProductApi.Models.Property", "Property")
                        .WithMany("PropertyValues")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("microStore.Services.ProductApi.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("microStore.Services.ProductApi.Models.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("microStore.Services.ProductApi.Models.Property", b =>
                {
                    b.Navigation("PropertyValues");
                });

            modelBuilder.Entity("microStore.Services.ProductApi.Models.PropertyType", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
